FROM python:3

RUN pip install pandas

RUN pip install sqlalchemy

RUN pip install psycopg2

RUN pip install sklearn

RUN pip install joblib

RUN pip install flask

RUN pip install flask-cors

COPY . /

CMD [ "python", "./api.py" ]
